server:
  port: 9000

spring:
  application:
    name: auth
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/nwt_auth
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

jwt:
  header-title: Authorization
  token-prefix: "Bearer "
  secret-key: ${JWT_SECRET_KEY}
  authorities-key: USER_AUTHORITIES
  token-validity-time: PT30M
